### ISSUE TITLE
有人在CSDN发表此文，并标注原创

### ISSUE THREAD

**Issue by bahuangcn** [LeoMobileDeveloper/ReactNativeMaterials#1]
冒昧打扰！
因在别处看到此文被标为原创，不知以下链接是否为您本人发表。
[CSDN](http://blog.csdn.net/xiangzhihong8/article/details/78909135)
[阿里云栖社区](https://yq.aliyun.com/articles/319149?spm=5176.8091938.0.0.pfuVBV)

**Comment by LeoMobileDeveloper** [comment]
@bahuangcn 确实不是我，我去怼他，哈哈
